version: v1.0.0
networks:
  intern-network:
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["${COMMAND:-dev}"]
    ports:
      - "${PORT}:${PORT_CONTAINER}"
    volumes:
      - ./.env:/app/.env
      - ./src:/app/src
      - ./dist:/app/dist
      - ./public:/app/public
      - ./bin:/app/bin
    env_file:
      - ./.env
    networks:
      - intern-network
    depends_on:
      - database
  database:
    image: postgres:17.2-alpine3.21
    env_file: ./.env
    networks:
      - intern-network
