config:
  use: "dev"
databases:
  dev:
    client: "postgresql"
    user: root
    name: postgres
    host: database
    port: 5432
    password: "1234"
  test:
    client: "postgresql"
    user: root
    name: postgres
    host: testdatabase
    port: 5432
    password: "1234"