config:
  use: "${USE_DATABASE}"
databases:
  dev:
    client: "postgresql"
    user: root
    name: postgres
    host: database
    port: 5432
    password: "1234"
  prod:
    env: 'config/env/.env.prod'